kind: task_template
id: common.prepare_requirements_spec
version: 1.0.0
title: Подготовить техническое задание
type: composite
status: active
domain: common
children:
  - id: request_analysis
    task: common.analyze_request@1.0.0
  - id: solution_analysis
    task: common.analyze_solution@1.0.0
  - id: spec_generation
    task: common.generate_requirements_spec@1.0.0
  - id: spec_review
    task: common.review_requirements_spec@1.0.0
slots:
  - id: project.additional_analysis
    title: Дополнительный анализ проекта
